# Generated by Django 5.1.5 on 2025-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sum_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
