# Generated by Django 5.1.6 on 2025-03-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0002_delivery_delivery_aggregator'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_items',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_aggregator',
            field=models.CharField(choices=[('glovo', 'Glovo'), ('wolt', 'Wolt'), ('choco', 'Chocofood'), ('yandex', 'YandexEda'), ('abr', 'abr+')], default='wolt', max_length=10),
        ),
    ]
