# Generated by Django 5.1.6 on 2025-03-12 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0004_delivery_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='client_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
