# Generated by Django 5.1.6 on 2025-03-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0006_client_remove_delivery_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payout_tracking.client'),
        ),
    ]
