# Generated by Django 5.1.6 on 2025-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0007_delivery_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_first_name', models.CharField(max_length=100)),
                ('courier_last_name', models.CharField(max_length=100)),
                ('courier_gender', models.CharField(choices=[('male', 'Man'), ('female', 'Woman')], default='male', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='couriers',
            field=models.ManyToManyField(to='payout_tracking.courier'),
        ),
    ]
