# Generated by Django 5.1.6 on 2025-03-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0008_courier_delivery_couriers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_aggregator',
            field=models.CharField(choices=[('glovo', 'Glovo'), ('wolt', 'Wolt'), ('choco', 'Chocofood'), ('yandex', 'YandexEda'), ('abr', 'abr+')], default='Wolt', max_length=10),
        ),
    ]
