# Generated by Django 5.1.6 on 2025-03-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0010_alter_delivery_couriers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_color', models.CharField(max_length=20)),
                ('bag_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='bag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payout_tracking.bagcolor'),
        ),
    ]
