# Generated by Django 5.1.6 on 2025-04-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout_tracking', '0011_bagcolor_courier_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=60)),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
